Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedColonStyle: table  

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
